server:
  port: 8080
spring:
  application:
    name: grove-cache-service
  data:
    redis:
      host: localhost
      port: 6379
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
